export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";

export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";

export const ALL_PRODUCT_FAILURE = "ALL_PRODUCT_FAILURE";

export const ALL_PRODUCT_DETAILS_REQUEST = "ALL_PRODUCT_DETAILS_REQUEST";

export const ALL_PRODUCT_DETAILS_SUCCESS = "ALL_PRODUCT_DETAILS_SUCCESS";

export const ALL_PRODUCT_DETAILS_FAILURE = "ALL_PRODUCT_DETAILS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";

export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";

export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";

export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";

export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const SHIPPING_INFO = "SHIPPING_INFO";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";

export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";

export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";

export const MY_ORDER_FAILURE = "MY_ORDER_FAILURE";

export const SINGLE_ORDER_REQUEST = "SINGLE_ORDER_REQUEST";

export const SINGLE_ORDER_FAILURE = "SINGLE_ORDER_FAILURE";

export const SINGLE_ORDER_SUCCESS = "SINGLE_ORDER_SUCCESS";

export const REVIEW_REQUEST = "REVIEW_REQUEST";

export const REVIEW_SUCCESS = "REVIEW_SUCCESS";

export const REVIEW_FAIL = "REVIEW_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";

export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";

export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";

export const CREATE_INVENTORY_REQUEST = "CREATE_INVENTORY_REQUEST";

export const CREATE_INVENTORY_SUCCESS = "CREATE_INVENTORY_SUCCESS";

export const CREATE_INVENTORY_FAILURE = "CREATE_INVENTORY_FAILURE";

export const DELETE_REQUEST = "DELETE_REQUEST";

export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const DELETE_FAILURE = "DELETE_FAILURE";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";

export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";

export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";

export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";

export const ADMIN_ORDERS_FAILURE = "ADMIN_ORDERS_FAILURE";

export const DELETE_ORDERS_FAILURE = "DELETE_ORDERS_FAILURE";

export const DELETE_ORDERS_REQUEST = "DELETE_ORDERS_REQUEST";

export const DELETE_ORDERS_SUCCESS = "DELETE_ORDERS_SUCCESS";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";

export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";

export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";

export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";

export const ADMIN_USERS_FAILURE = "ADMIN_USERS_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";


export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST";

export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS";

export const ADMIN_USER_FAILURE = "ADMIN_USER_FAILURE";


export const ADMIN_REVIEWS_REQUEST = "ADMIN_REVIEWS_REQUEST";

export const ADMIN_REVIEWS_SUCCESS = "ADMIN_REVIEWS_SUCCESS";

export const ADMIN_REVIEWS_FAILURE = "ADMIN_REVIEWS_FAILURE";


export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";

export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";

export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE";


